# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c582f09cec5dd8042230ed0d2694407cc1b7dd8f20defd0d8dadf670e4d765c1f90425d580b34b18fa11836c7e26793c98e651ad06f39fcf7f8a32b54f293616

test:
  secret_key_base: f2ddadef6ce31934d49e37e726b752e8d9b1a130fcc50d4a606a20c3cdb8c279532b6cfa4d13cb0b577f377a0d5dd9ee409927d61f4f20431a2ad20941870061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
